name = "Mauro"
author = "RBkey"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "868f6ca3d67e90b31a960962ccf0d563beff88df7010af1a050c469c8a2c3c4d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
