name = "Mauro"
author = "RBkey"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47b35a3e595d15b0859b8310a123df3fa14861d131fcc52d9fb52a2692a74ba6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
