name = "Mauro"
author = "RBkey"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1747a10b0de9e9a5937e57430d0b5d34cbd585eee61b5f71092de4193cb6497c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
